### ISSUE TITLE
[feature request] make howdoi.el can let user configure search engine URL.

### ISSUE THREAD

**Issue by stardiviner** [atykhonov/emacs-howdoi#3]
I can not reach google.com here, So I wish to use DuckDuckGo, Bing, or some other search engines.
Make this into a custom option is better instead of static internal URL.

**Comment by atykhonov** [comment]
Hello!

I didn't find the way to make request to the DockDuckGo (for example: https://duckduckgo.com/?q=site%3Astackoverflow.com%20python%20read%20file) and retrieve the links from result. The search result populates by means of javascript. Also I took a look to the API but didn't find the way to make a complex (with several keywords separated by space) request. I've tried http://api.duckduckgo.com/?q=python+read+file&format=json&pretty=1 but that always returns empty result.

**Comment by stardiviner** [comment]
I see. thanks for your checking out.
