### ISSUE TITLE
answer not getting popped to buffer

### ISSUE THREAD

**Issue by izahn** [atykhonov/emacs-howdoi#4]
I installed from MELPA with emacs 24.4.2, and find that howoi-query and howdoi-query-line-at-point don't manage to put anything in the *How do I* buffer. howdoi-query-insert-code-snippet-at-point and hodoi-query-line-at-point-replace-by-code-snippet both work, so retrieving the answer from SO seams to be fine, but for some reason it is not getting inserted into the actual *How do I* buffer. Please let me know if you need further details in order to reproduce.

**Comment by atykhonov** [comment]
Do you see any error? What if to `M-x toggle-debug-on-error` and than to try `howdoi-query` what I'll get?

**Comment by izahn** [comment]
No, there is no error. I've recorded a screen cast showing what I did and what happens, available at http://izahn.crabdance.com/~izahn/howdoi_use_howdoi.ogv

**Comment by atykhonov** [comment]
Thank you for the screen cast! I've got another error before... But recently I was getting the same blank buffer. I fixed that issue and it works now well.

Thank you for the bug report!
